import type { Metadata } from "next";
import "./globals.css";
import Header from "@/components/header/Header";
import Footer from "@/components/footer/Footer";
import Providers from "@/components/providers";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased w-screen min-h-screen flex flex-col items-center overflow-x-hidden relative -z-20`}
      >
        <Header />
        <Providers>
          <main className="flex-grow w-full flex flex-col items-center relative -z-50">
            {children}
          </main>
        </Providers>
        <Footer />
      </body>
    </html>
  );
}
